### ISSUE TITLE
Feature request: configuration of PHPUnit

### ISSUE THREAD

**Issue by PhilippImhof** [lmscloud-io/mdlcode-docs#1]
When MDLCode is installed and enabled, it shows a code lens "Run all tests" or "Run test" in files where PHPUnit tests are defined. However, the same lens might already be there from other extensions, e.g. Yet-another-PHPUnit. It would be nice to add an option where the user can hide the code lens.

Also, MDLCode uses `php admin/tool/phpunit/cli/util.php --run` to run those unit tests and this cannot be changed. However, in a test class that has `@runTestsInSeparateProcesses` set, tests will not be run, probably due to a bug in the utility script. Again, it would be nice to add an option where the user can configure how they would like their tests to be run.

**Comment by lmscloud-io** [comment]
Hello @PhilippImhof , thank for the suggestion.

This feature is implemented in version 1.0.19 released today (2023-12-17). Documentation is available here: https://mdlcode.dev/docs/configuration#enabled-features

P.S. it would be great if you can report the problem with `php admin/tool/phpunit/cli/util.php --run` in Moodle tracker.
