### ISSUE TITLE
Quality of Life: New string wizard form improvements

### ISSUE THREAD

**Issue by FMCorz** [lmscloud-io/mdlcode-docs#11]
Just a few suggestions to improve the UX of the new string form.

1. Move the "Not sure what these fields mean? Checkout (doclink)" to the end of the form, so that its link is not the next `tab` stop.
2. Empty the "Text" instead of setting to the string code by default. I personally always overwrite it. Alternatively, select the whole string by default.
3. Support CTRL + Enter to submit the form directly from the "Text" field

Thanks!

**Comment by marinaglancy** [comment]
Thanks for suggestion, Fred.
This is added in v1.0.33 (released today)

1. all doc links now have tabindex=-1 
2. I chose selecting the whole string
3. Ctrl+Enter is supported when a focus is inside a text field. It was quite tricky to implement it anywhere in the form, I hope it's an acceptable compromise

**Comment by FMCorz** [comment]
Brilliant, thank you!
