### ISSUE TITLE
Feature request: Allow configuration of new file template

### ISSUE THREAD

**Issue by andrewnicols** [lmscloud-io/mdlcode-docs#13]
I'd like to drop the copyright year from the new file template per https://tracker.moodle.org/browse/MDL-81747

**Comment by marinaglancy** [comment]
Thanks for suggestion @andrewnicols  . In version 1.0.34 released 2024-09-01 I added a new setting "Use Year In Copyright" (mdlcode.useYearInCopyright) . It is true by default so that it does not change behaviour for the existing users but can be turned off.
