### ISSUE TITLE
Add support for \core\di

### ISSUE THREAD

**Issue by andrewnicols** [lmscloud-io/mdlcode-docs#3]
Example:

```php
\core\di::get(\core\hook\manager::class)->dispatch($hook);
```

**Comment by lmscloud-io** [comment]
Hi Andrew, v 1.0.26 adds support for the expressions like:

```
\core\di::get(\core\hook\manager::class)->dispatch($hook); // detects hook emitter
\core\di::get(moodle_database::class)->get_records('course'); // detects reference to the table 'course'
\core\di::get(core_string_manager::class)->get_string('yes'); // detects reference to the string 'yes'
```

adding '.phpstorm.meta.php' to the moodle root like you suggested, allows to work with di instances as if they were normal classes, there is no need to additionally support it in mdlcode. Maybe we should add it to the codebase in 4.4?

**Comment by lmscloud-io** [comment]
![dihook](https://github.com/lmscloud-io/mdlcode-docs/assets/128620190/5f391aa5-bff3-45dd-b82c-119be6777313)
