### ISSUE TITLE
Feature request: Keyboard shortcuts to run tests

### ISSUE THREAD

**Issue by NoelDeMartin** [lmscloud-io/mdlcode-docs#6]
It would be nice to be able to run Behat and PHPUnit tests by using a keyboard shortcut, similar to [Better Jest](https://marketplace.visualstudio.com/items?itemName=CoachRichbart.better-jest) and [Better PHPUnit](https://marketplace.visualstudio.com/items?itemName=calebporzio.better-phpunit).

**Comment by lmscloud-io** [comment]
Hi Noel, thanks for the suggestion.
This is implemented in version 1.0.32 (released today)
