### ISSUE TITLE
Plugins explorer to hide folders/files hidden in regular explorer

### ISSUE THREAD

**Issue by FMCorz** [lmscloud-io/mdlcode-docs#9]
The list of files and folders in the plugins explorer view includes files and folders that are otherwise hidden in the regular explorer. The most obvious are the `.vscode` and `.git` folders. Others like `node_modules` are displayed, which is fine as it is consistent with the explorer. I am unsure which settings control the visibility of these.

**Comment by lmscloud-io** [comment]
hi Fred, in the regular explorer it is controled by settings `files.exclude` and `explorer.excludeGitIgnore` . I can exclude them from plugins view too in mdlcode

**Comment by FMCorz** [comment]
Thanks, my `files.exclude` does indeed include `.git` and `.vscode` amongst others. I did not enable `explorer.excludeGitIgnore` as I find it useful to see those files, especially `config.php`.

**Comment by marinaglancy** [comment]
Thanks for suggestion, Fred.
This is added in v1.0.33 (released today)
I respect filex.exclude but not explorer.excludeGitIgnore. I thought that it is not worth troubles, and like you said, nobody working with Moodle wants to hide config.php anyway so nobody has it enabled
